export const iconsType = [
  { name: 'home' },
  { name: 'office' },
  { name: 'newspaper' },
  { name: 'pencil' },
  { name: 'quill' },
  { name: 'droplet' },
  { name: 'images' },
  { name: 'camera' },
  { name: 'headphones' },
  { name: 'music' },
  { name: 'video-camera' },
  { name: 'phone' },
  { name: 'man' },
  { name: 'woman' },
  { name: 'happy' },
  { name: 'hipster' },
  { name: 'sleepy' },
  { name: 'checkmark' },
];
